### ISSUE TITLE
Cell301 get_paths function

### ISSUE THREAD

**Issue by zekikus** [naszilla/naszilla#23]
Hi,

I have a question for **get_paths** function in **cell_301.py**. In the second loop (cell_301.py -> get_paths function -> Line 180), you are iterating each tuple item in the self.arch. But in this loop, the last element of the list (last edge, ops pair) is not visited. For example, suppose I have an example like the one below.

self.arch = {[(1, 2), (0, 1), (0, 2), (2, 0), (2, 2), (3, 1), (4, 3), (0, 2)], 
                   [(0, 3), (1, 4), (0, 6), (2, 1), (1, 4), (3, 6), (0, 5), (4, 5)]}

In the inner loop between lines 181 and 193, the last elements of the list are not included because the loop is defined like this: 

`for j in range(len(OPS)):`

I think it needs to be changed to:

`for j in range(len(OPS) + 1):`

Thanks,

![Ekran Alıntısı](https://user-images.githubusercontent.com/7164423/142357494-89f67a9a-2ed7-4dcf-8704-84f04d930010.PNG)

**Comment by crwhite14** [comment]
Yes, I think you are right. It looks like in an [earlier version](https://github.com/naszilla/bananas/blob/e2c12ade9e290e309e206fc3c8f97a373a136a81/darts/arch.py#L10), OPS was size 8, but later it was changed to size 7 to be compatible with nas-bench-301. I just made the change, thanks.
